#!/usr/bin/env python3
"""Write src/config/git_info.h with the build number and git commit.

The firmware component's CMakeLists.txt runs this before every build. The
header is rewritten only when its content changes, so an unchanged tree builds
incrementally.

Build number: SMART_GRIND_BUILD_NUMBER, when set to a positive integer, is used
as is; CI and release builds set it so V1 and V2 from one run report the same
number. Otherwise the number in .build_number is reused, and advanced by one
when SMART_GRIND_INCREMENT_BUILD=1.
"""

import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
HEADER_PATH = PROJECT_ROOT / "src" / "config" / "git_info.h"
BUILD_NUMBER_PATH = PROJECT_ROOT / ".build_number"


def git(*arguments: str) -> str:
    """Output of a git command in the project, or "" when git is unavailable."""
    try:
        result = subprocess.run(["git", *arguments], cwd=PROJECT_ROOT,
                                capture_output=True, text=True, check=False)
    except OSError:
        return ""
    return result.stdout.strip() if result.returncode == 0 else ""


def git_info() -> tuple:
    """Short commit (with "+" for uncommitted changes) and branch name."""
    commit = git("rev-parse", "--short=7", "HEAD") or "unknown"
    branch = git("rev-parse", "--abbrev-ref", "HEAD") or "unknown"
    if commit != "unknown" and git("status", "--porcelain"):
        commit += "+"
    return commit, branch


def build_number() -> int:
    override = os.environ.get("SMART_GRIND_BUILD_NUMBER", "").strip()
    if override:
        if override.isdigit() and int(override) >= 1:
            return int(override)
        print("Warning: SMART_GRIND_BUILD_NUMBER must be a positive integer; "
              "using the local build counter instead", file=sys.stderr)

    number = 1
    try:
        number = int(BUILD_NUMBER_PATH.read_text().strip())
        if os.environ.get("SMART_GRIND_INCREMENT_BUILD", "").strip() == "1":
            number += 1
    except (OSError, ValueError):
        pass
    try:
        BUILD_NUMBER_PATH.write_text(str(number))
    except OSError as error:
        print(f"Warning: could not write {BUILD_NUMBER_PATH}: {error}", file=sys.stderr)
    return number


def main() -> int:
    commit, branch = git_info()
    number = build_number()
    identity = (
        f'#define GIT_COMMIT_ID "{commit}"\n'
        f'#define GIT_BRANCH "{branch}"\n'
        f"#define BUILD_NUMBER {number}\n"
    )
    try:
        existing = HEADER_PATH.read_text()
    except OSError:
        existing = ""
    # The timestamp alone changing must not rebuild everything that includes it.
    if identity in existing:
        return 0

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    HEADER_PATH.write_text(
        "#pragma once\n\n"
        "// Generated by tools/build-scripts/build_info.py - do not edit.\n\n"
        f"{identity}"
        f'#define BUILD_TIMESTAMP "{timestamp}"\n'
    )
    print(f"Build information: build #{number}, {commit} on {branch}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
