#include "device_web_server.h"
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <cstdio>
#include <cstring>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <esp_system.h>
#include "../system/device_info.h"
#include "../system/timing.h"

#include <HTTPClient.h>
#include "../storage/filesystem.h"
#include <Update.h>
#include <WiFi.h>
#include <WiFiClientSecure.h>
#include <algorithm>
#include <ctime>
#include <functional>
#include <new>
#include <esp_heap_caps.h>
#include <esp_ota_ops.h>
#include <vector>

#include "../config/build_info.h"
#include "../config/constants.h"
#include "../controllers/grind_controller.h"
#include "../bluetooth/manager.h"
#include "../hardware/hardware_manager.h"
#include "../logging/grind_logging.h"
#include "../logging/diagnostic_log.h"
#include "network_manager.h"
#include "device_api.h"
#include "ota_stream.h"

namespace {
const char* network_state_name(NetworkState state) {
    switch (state) {
        case NetworkState::WIFI_DISABLED: return "disabled";
        case NetworkState::WIFI_NO_CREDENTIALS: return "no_credentials";
        case NetworkState::WIFI_CONNECTING: return "connecting";
        case NetworkState::WIFI_CONNECTED: return "connected";
        case NetworkState::WIFI_RETRY_WAIT: return "retry_wait";
        case NetworkState::WIFI_SETUP_REQUIRED: return "setup_required";
        case NetworkState::WIFI_SETUP_AP: return "setup_ap";
    }
    return "unknown";
}

String json_escape(const String& value) {
    String escaped;
    escaped.reserve(value.length() + 8);
    for (size_t i = 0; i < value.length(); ++i) {
        const char ch = value[i];
        switch (ch) {
            case '"': escaped += "\\\""; break;
            case '\\': escaped += "\\\\"; break;
            case '\b': escaped += "\\b"; break;
            case '\f': escaped += "\\f"; break;
            case '\n': escaped += "\\n"; break;
            case '\r': escaped += "\\r"; break;
            case '\t': escaped += "\\t"; break;
            default:
                if (static_cast<uint8_t>(ch) >= 0x20) escaped += ch;
                break;
        }
    }
    return escaped;
}

bool request_origin_allowed(AsyncWebServerRequest* request) {
    if (!request || !request->hasHeader("Origin")) return true;
    const AsyncWebHeader* origin = request->getHeader("Origin");
    return origin && origin->value() == ("http://" + request->host());
}

bool history_is_busy(const GrindController* controller) {
    if (!controller) return false;
    const GrindPhase phase = controller->get_phase();
    const bool result_is_waiting = phase == GrindPhase::COMPLETED || phase == GrindPhase::TIMEOUT;
    // A completed result remains on screen until the user dismisses it, but the
    // saved session is safe to read as soon as the logger has finished writing.
    return (phase != GrindPhase::IDLE && !result_is_waiting) || grind_logger.is_logging_active();
}

struct OtaRequestState {
    bool success;
    bool complete;
    OperationInterlock::Token token;
};

struct ScreensaverUploadState {
    bool success;
    bool complete;
};

constexpr uint32_t OTA_REBOOT_DELAY_MS = 1500;
constexpr uint32_t OTA_PREPARE_TIMEOUT_MS = 15000;
constexpr uint32_t OTA_READY_WINDOW_MS = 30000;
constexpr size_t OTA_MIN_INTERNAL_HEAP = 64U * 1024U;
constexpr size_t OTA_DOWNLOAD_TASK_STACK = 12U * 1024U;
constexpr uint32_t UPDATE_CHECK_INTERVAL_MS = 30U * 60U * 1000U;
constexpr uint32_t UPDATE_CHECK_RETRY_MS = 5U * 60U * 1000U;
constexpr size_t UPDATE_CHECK_TASK_STACK = 10U * 1024U;
// GitHub Pages mirrors every published release beneath this versioned path.
// Using the mirror avoids the github.com -> release-assets.githubusercontent.com
// redirect during a memory-constrained TLS session while retaining the exact
// audited release binaries generated by the release workflow.
constexpr char GITHUB_RELEASE_MIRROR_BASE[] =
    "https://clinteastman.github.io/smart-grind-by-weight/firmware/";
constexpr char LATEST_RELEASE_MANIFEST_URL[] =
    "https://clinteastman.github.io/smart-grind-by-weight/firmware/latest.json";
extern const uint8_t x509_crt_imported_bundle_bin_start[]
    asm("_binary_x509_crt_bundle_start");
extern const uint8_t x509_crt_imported_bundle_bin_end[]
    asm("_binary_x509_crt_bundle_end");
UpdateClass web_firmware_update;

bool valid_release_tag(const String& tag) {
    if (tag.length() < 6 || tag.length() > 24 || tag[0] != 'v') return false;
    uint8_t dots = 0;
    for (size_t i = 1; i < tag.length(); ++i) {
        if (tag[i] == '.') {
            if (i == 1 || i + 1 == tag.length() || tag[i - 1] == '.') return false;
            ++dots;
        } else if (tag[i] < '0' || tag[i] > '9') {
            return false;
        }
    }
    return dots == 2;
}

bool parse_semver(const String& value, uint16_t& major, uint16_t& minor, uint16_t& patch) {
    const size_t offset = value.startsWith("v") ? 1U : 0U;
    const int first_dot = value.indexOf('.', static_cast<unsigned int>(offset));
    const int second_dot = first_dot < 0 ? -1 : value.indexOf('.', first_dot + 1);
    if (first_dot <= static_cast<int>(offset) || second_dot <= first_dot + 1 ||
        second_dot + 1 >= static_cast<int>(value.length())) {
        return false;
    }
    for (size_t i = offset; i < value.length(); ++i) {
        if (i == static_cast<size_t>(first_dot) || i == static_cast<size_t>(second_dot)) continue;
        if (!isDigit(value[i])) return false;
    }
    const unsigned long parsed_major = value.substring(offset, first_dot).toInt();
    const unsigned long parsed_minor = value.substring(first_dot + 1, second_dot).toInt();
    const unsigned long parsed_patch = value.substring(second_dot + 1).toInt();
    if (parsed_major > UINT16_MAX || parsed_minor > UINT16_MAX || parsed_patch > UINT16_MAX) {
        return false;
    }
    major = static_cast<uint16_t>(parsed_major);
    minor = static_cast<uint16_t>(parsed_minor);
    patch = static_cast<uint16_t>(parsed_patch);
    return true;
}

String json_string_value(const String& json, const char* key) {
    const String needle = String('"') + key + '"';
    const int key_pos = json.indexOf(needle);
    const int colon = key_pos < 0 ? -1 : json.indexOf(':', key_pos + needle.length());
    const int opening_quote = colon < 0 ? -1 : json.indexOf('"', colon + 1);
    const int closing_quote = opening_quote < 0 ? -1 : json.indexOf('"', opening_quote + 1);
    if (opening_quote < 0 || closing_quote <= opening_quote + 1) return String();
    return json.substring(opening_quote + 1, closing_quote);
}

bool json_bool_value(const String& json, const char* key, bool& value) {
    const String needle = String('"') + key + '"';
    const int key_pos = json.indexOf(needle);
    const int colon = key_pos < 0 ? -1 : json.indexOf(':', key_pos + needle.length());
    if (colon < 0) return false;
    int value_pos = colon + 1;
    while (value_pos < static_cast<int>(json.length()) && isspace(json[value_pos])) ++value_pos;
    if (json.startsWith("true", value_pos)) {
        value = true;
        return true;
    }
    if (json.startsWith("false", value_pos)) {
        value = false;
        return true;
    }
    return false;
}
}

DeviceWebServer device_web_server;

void DeviceWebServer::init(HardwareManager* hardware_manager, GrindController* grind_controller,
                           BluetoothManager* bluetooth_manager, ProfileController* profile_controller) {
    if (initialized_) return;
    hardware_manager_ = hardware_manager;
    grind_controller_ = grind_controller;
    bluetooth_manager_ = bluetooth_manager;
    device_api.init(&server_, hardware_manager_, grind_controller_, profile_controller);
    configure_routes();
    initialized_ = true;
}

void DeviceWebServer::begin() {
    if (!initialized_ || started_) return;
    // AsyncServer::begin() enters lwIP immediately. Calling it while Wi-Fi is
    // still WIFI_MODE_NULL reaches an uninitialised lwIP semaphore and aborts
    // in xQueueSemaphoreTake on ESP32 Arduino 3.x.
    if (WiFi.getMode() == WIFI_MODE_NULL) return;
    server_.begin();
    started_ = true;
    LOG_BLE("[WEB] HTTP service listening on port 80\n");
}

void DeviceWebServer::update() {
    device_api.update();
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    OtaPreparationState preparation = ota_preparation_state_.load();
    if (preparation == OtaPreparationState::REQUESTED) {
        const bool unsafe = ota_active_.load() || !grind_controller_ ||
                            grind_controller_->is_active() ||
                            (bluetooth_manager_ && bluetooth_manager_->is_transfer_active());
        if (unsafe) {
            recover_from_ota_failure();
        } else {
            if (bluetooth_manager_ && bluetooth_manager_->is_enabled()) {
                LOG_BLE("[WEB OTA] Temporarily disabling Bluetooth to free update memory\n");
                bluetooth_manager_->disable();
                ota_bluetooth_stopped_.store(true);
            }
            if (heap_caps_get_free_size(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT) >=
                OTA_MIN_INTERNAL_HEAP) {
                ota_preparation_deadline_ms_.store(millis() + OTA_READY_WINDOW_MS);
                ota_preparation_state_.store(OtaPreparationState::READY);
                LOG_BLE("[WEB OTA] Update preparation complete\n");
            } else if (static_cast<int32_t>(millis() - ota_preparation_deadline_ms_.load()) >= 0) {
                LOG_BLE("[WEB OTA] Could not recover enough internal memory\n");
                recover_from_ota_failure();
            }
        }
    } else if (preparation == OtaPreparationState::READY && !ota_active_.load() &&
               static_cast<int32_t>(millis() - ota_preparation_deadline_ms_.load()) >= 0) {
        LOG_BLE("[WEB OTA] Prepared upload expired\n");
        recover_from_ota_failure();
    }

    if (on_device_update_pending_.load() && is_ota_ready()) {
        const String tag = latest_release_tag();
        on_device_update_pending_.store(false);
        if (tag.isEmpty() || !start_github_ota(tag)) {
            LOG_BLE("[WEB OTA] Could not start requested on-device update\n");
            recover_from_ota_failure();
        }
    }

    const uint32_t now = millis();
    const uint32_t interval = firmware_update_state_.load() == FirmwareUpdateState::FAILED
                                  ? UPDATE_CHECK_RETRY_MS
                                  : UPDATE_CHECK_INTERVAL_MS;
    const uint32_t last_check = last_firmware_update_check_ms_.load();
    const bool check_due = last_check == 0 || now - last_check >= interval;
    const bool check_safe = network_manager.is_connected() && !is_ota_active() &&
                            ota_preparation_state_.load() == OtaPreparationState::IDLE &&
                            (!grind_controller_ || !grind_controller_->is_active()) &&
                            (!bluetooth_manager_ || !bluetooth_manager_->is_transfer_active()) &&
                            heap_caps_get_free_size(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT) >=
                                OTA_MIN_INTERNAL_HEAP;
    if (check_due && check_safe) {
        bool expected_inactive = false;
        if (firmware_update_check_active_.compare_exchange_strong(expected_inactive, true)) {
            firmware_update_state_.store(FirmwareUpdateState::CHECKING);
            if (xTaskCreate(firmware_update_check_task, "update_check", UPDATE_CHECK_TASK_STACK,
                            nullptr, 1, nullptr) != pdPASS) {
                firmware_update_check_active_.store(false);
                firmware_update_state_.store(FirmwareUpdateState::FAILED);
                last_firmware_update_check_ms_.store(now);
            }
        }
    }
    if (reboot_pending_.load() &&
        static_cast<int32_t>(millis() - reboot_at_ms_.load()) >= 0) {
        LOG_BLE("[WEB OTA] Restarting device\n");
    fflush(stdout);
        esp_restart();
    }
}

String DeviceWebServer::latest_release_tag() const {
    if (latest_version_major_.load() == 0 && latest_version_minor_.load() == 0 &&
        latest_version_patch_.load() == 0) {
        return String();
    }
    char tag[25];
    snprintf(tag, sizeof(tag), "v%u.%u.%u", latest_version_major_.load(),
             latest_version_minor_.load(), latest_version_patch_.load());
    return String(tag);
}

bool DeviceWebServer::install_available_update() {
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    if (!firmware_update_available() || latest_release_tag().isEmpty() ||
        !network_manager.is_connected() || ota_active_.load() ||
        ota_preparation_state_.load() != OtaPreparationState::IDLE ||
        (grind_controller_ && grind_controller_->is_active()) ||
        (bluetooth_manager_ && bluetooth_manager_->is_transfer_active())) {
        return false;
    }
    if (!request_ota_preparation()) return false;
    on_device_update_pending_.store(true);
    return true;
}

void DeviceWebServer::firmware_update_check_task(void*) {
    device_web_server.perform_firmware_update_check();
    device_web_server.firmware_update_check_active_.store(false);
    vTaskDelete(nullptr);
}

void DeviceWebServer::perform_firmware_update_check() {
    FirmwareUpdateState result = FirmwareUpdateState::FAILED;
    WiFiClientSecure secure_client;
    secure_client.setCACertBundle(
        x509_crt_imported_bundle_bin_start,
        static_cast<size_t>(x509_crt_imported_bundle_bin_end -
                            x509_crt_imported_bundle_bin_start));
    secure_client.setTimeout(10000);
    secure_client.setHandshakeTimeout(10);

    HTTPClient http;
    http.useHTTP10(true);
    http.setConnectTimeout(10000);
    http.setTimeout(10000);
    http.setFollowRedirects(HTTPC_STRICT_FOLLOW_REDIRECTS);
    http.setUserAgent("SmartGrind-UpdateCheck/1");
    http.addHeader("Cache-Control", "no-cache");
    if (http.begin(secure_client, LATEST_RELEASE_MANIFEST_URL)) {
        const int status = http.GET();
        if (status == HTTP_CODE_OK) {
            const int content_length = http.getSize();
            if (content_length > 0 && content_length <= 512) {
                const String manifest = http.getString();
                const String tag = json_string_value(manifest, "tag");
                bool v1_available = false;
                bool v2_available = false;
                uint16_t major = 0;
                uint16_t minor = 0;
                uint16_t patch = 0;
                if (valid_release_tag(tag) && parse_semver(tag, major, minor, patch) &&
                    json_bool_value(manifest, "v1", v1_available) &&
                    json_bool_value(manifest, "v2", v2_available)) {
                    const bool asset_available = HW_DISPLAY_VARIANT_V2
                                                     ? v2_available
                                                     : v1_available;
                    uint16_t current_major = 0;
                    uint16_t current_minor = 0;
                    uint16_t current_patch = 0;
                    if (asset_available && parse_semver(BUILD_FIRMWARE_VERSION, current_major,
                                                        current_minor, current_patch)) {
                        latest_version_major_.store(major);
                        latest_version_minor_.store(minor);
                        latest_version_patch_.store(patch);
                        const bool newer = major > current_major ||
                                           (major == current_major && minor > current_minor) ||
                                           (major == current_major && minor == current_minor &&
                                            patch > current_patch);
                        result = newer ? FirmwareUpdateState::AVAILABLE
                                       : FirmwareUpdateState::CURRENT;
                    }
                }
            }
        }
        http.end();
    }
    last_firmware_update_check_ms_.store(millis());
    firmware_update_state_.store(result);
    const String latest_tag = latest_release_tag();
    LOG_BLE("[WEB OTA] Firmware update check: %s%s%s\n",
            result == FirmwareUpdateState::AVAILABLE ? "available" :
            result == FirmwareUpdateState::CURRENT ? "current" : "failed",
            latest_tag.isEmpty() ? "" : " ", latest_tag.c_str());
}

bool DeviceWebServer::is_ota_ready() const {
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    return ota_preparation_state_.load() == OtaPreparationState::READY &&
           static_cast<int32_t>(millis() - ota_preparation_deadline_ms_.load()) < 0 &&
           operation_interlock().owns(operation_token_) &&
           initialized_ && network_manager.is_connected() && !is_ota_active() &&
           (!grind_controller_ || !grind_controller_->is_active()) &&
           (!bluetooth_manager_ || !bluetooth_manager_->is_transfer_active()) &&
           heap_caps_get_free_size(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT) >= OTA_MIN_INTERNAL_HEAP;
}

bool DeviceWebServer::request_ota_preparation() {
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    if (!initialized_ || !network_manager.is_connected() || is_ota_active() ||
        firmware_update_check_active_.load() ||
        ota_preparation_state_.load() != OtaPreparationState::IDLE ||
        !grind_controller_ || grind_controller_->is_active() ||
        (bluetooth_manager_ && bluetooth_manager_->is_transfer_active())) return false;
    const auto token = operation_interlock().try_acquire();
    if (!token) return false;
    operation_token_ = token;
    ota_failed_.store(false);
    ota_bluetooth_stopped_.store(false);
    ota_preparation_deadline_ms_.store(millis() + OTA_PREPARE_TIMEOUT_MS);
    ota_preparation_state_.store(OtaPreparationState::REQUESTED);
    return true;
}

void DeviceWebServer::recover_from_ota_failure() {
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    if (ota_active_.load()) return;
    on_device_update_pending_.store(false);
    ota_preparation_state_.store(OtaPreparationState::IDLE);
    if (ota_bluetooth_stopped_.exchange(false)) {
        // Arduino BLE retains its server singleton across deinit(false). Re-enabling
        // in the same boot duplicates services and leaks heap, so recover through a
        // clean reboot into the still-valid running firmware instead.
        LOG_BLE("[WEB OTA] Scheduling clean recovery restart\n");
        reboot_at_ms_.store(millis() + OTA_REBOOT_DELAY_MS);
        reboot_pending_.store(true);
    }
    if (!reboot_pending_.load()) {
        operation_interlock().release(operation_token_);
        operation_token_ = 0;
    }
}

uint8_t DeviceWebServer::ota_progress_percent() const {
    const size_t total = ota_total_.load();
    if (!ota_active_.load() || total == 0) return 0;
    const size_t percent = (ota_received_.load() * 100U) / total;
    return static_cast<uint8_t>(percent > 100 ? 100 : percent);
}

void DeviceWebServer::configure_routes() {
    server_.on(AsyncURIMatcher::exact("/api/v1/status"), HTTP_GET, [](AsyncWebServerRequest* request) {
        AsyncResponseStream* response = request->beginResponseStream("application/json");
        const String hostname = json_escape(network_manager.hostname());
        const String device_id = json_escape(network_manager.device_id());
        const String network_name = json_escape(network_manager.network_name());
        const String ip_address = json_escape(network_manager.ip_address());
        response->printf(
            "{\"api\":\"v1\",\"device\":{\"id\":\"%s\",\"model\":\"ESP32-S3-Touch-AMOLED-1.64\",\"hardware_revision\":\"%s\"},"
            "\"capabilities\":{\"protocol\":1,\"transport\":\"websocket\",\"path\":\"/ws\",\"state_interval_ms\":100,"
            "\"commands\":[\"start\",\"start_manual\",\"stop\",\"dismiss\",\"tare\",\"select_profile\",\"set_mode\"]},"
            "\"firmware\":{\"version\":\"%s\",\"build\":%d,\"commit\":\"%s\"},"
            "\"network\":{\"state\":\"%s\",\"hostname\":\"%s\",\"ssid\":\"%s\",\"ip\":\"%s\"},"
            "\"system\":{\"uptime_ms\":%lu,\"free_heap\":%u,\"free_internal_heap\":%u,"
            "\"largest_internal_block\":%u,\"free_psram\":%u},"
            "\"ota\":{\"active\":%s,\"preparing\":%s,\"ready\":%s,\"progress\":%u,\"failed\":%s}}",
            device_id.c_str(),
            HW_DISPLAY_REVISION,
            BUILD_FIRMWARE_VERSION,
            BUILD_NUMBER,
            GIT_COMMIT_ID,
            network_state_name(network_manager.state()),
            hostname.c_str(),
            network_name.c_str(),
            ip_address.c_str(),
            static_cast<unsigned long>(millis()),
            static_cast<unsigned int>(device_info::free_heap_bytes()),
            static_cast<unsigned int>(heap_caps_get_free_size(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT)),
            static_cast<unsigned int>(heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT)),
            static_cast<unsigned int>(device_info::free_psram_bytes()),
            device_web_server.is_ota_active() ? "true" : "false",
            device_web_server.is_ota_preparing() ? "true" : "false",
            device_web_server.is_ota_ready() ? "true" : "false",
            device_web_server.ota_progress_percent(),
            device_web_server.ota_failed() ? "true" : "false");
        response->addHeader("Cache-Control", "no-store");
        request->send(response);
    });

    server_.on(AsyncURIMatcher::exact("/health"), HTTP_GET, [](AsyncWebServerRequest* request) {
        request->send(200, "text/plain", "ok");
    });

    server_.on(AsyncURIMatcher::exact("/api/v1/logs"), HTTP_GET, [](AsyncWebServerRequest* request) {
        AsyncWebServerResponse* response = request->beginResponse(
            200, "text/plain; charset=utf-8", diagnostic_log_snapshot());
        response->addHeader("Cache-Control", "private, no-store");
        request->send(response);
    });

    server_.on(AsyncURIMatcher::exact("/api/v1/history"), HTTP_GET, [this](AsyncWebServerRequest* request) {
        if (history_is_busy(grind_controller_) || ota_active_.load() ||
            (bluetooth_manager_ && bluetooth_manager_->is_transfer_active())) {
            request->send(409, "application/json", "{\"error\":\"History is busy; try again when the grinder is idle\"}");
            return;
        }

        std::vector<uint32_t> session_ids;
        FsFile directory = filesystem.open(GRIND_SESSIONS_DIR);
        if (directory && directory.isDirectory()) {
            FsFile entry = directory.openNextFile();
            while (entry) {
                const String name = entry.name();
                const int marker = name.lastIndexOf("session_");
                const int suffix = name.lastIndexOf(".bin");
                if (!entry.isDirectory() && marker >= 0 && suffix > marker + 8) {
                    const uint32_t id = name.substring(marker + 8, suffix).toInt();
                    if (id > 0) session_ids.push_back(id);
                }
                entry.close();
                entry = directory.openNextFile();
            }
            directory.close();
        }
        std::sort(session_ids.begin(), session_ids.end(), std::greater<uint32_t>());
        if (session_ids.size() > MAX_STORED_SESSIONS_FLASH) {
            session_ids.resize(MAX_STORED_SESSIONS_FLASH);
        }

        AsyncResponseStream* response = request->beginResponseStream("application/json");
        response->printf("{\"api\":\"v1\",\"storage_version\":%lu,\"sessions\":[",
                         static_cast<unsigned long>(grind_logger.get_session_storage_version()));
        bool first = true;
        for (uint32_t id : session_ids) {
            if (!grind_logger.validate_stored_session(id)) continue;
            char path[48];
            snprintf(path, sizeof(path), SESSION_FILE_FORMAT, static_cast<unsigned long>(id));
            FsFile file = filesystem.open(path, "r");
            TimeSeriesSessionHeader header{};
            GrindSession session{};
            if (!file || file.read(reinterpret_cast<uint8_t*>(&header), sizeof(header)) != sizeof(header) ||
                file.read(reinterpret_cast<uint8_t*>(&session), sizeof(session)) != sizeof(session) ||
                header.session_id != id || session.session_id != id) {
                if (file) file.close();
                continue;
            }
            file.close();
            char result[sizeof(session.result_status) + 1]{};
            memcpy(result, session.result_status, sizeof(session.result_status));
            if (!first) response->print(',');
            first = false;
            response->printf(
                "{\"id\":%lu,\"timestamp\":%lu,\"profile\":%u,\"mode\":\"%s\","
                "\"target_weight\":%.2f,\"target_time_ms\":%lu,\"final_weight\":%.2f,"
                "\"error_grams\":%.2f,\"time_error_ms\":%ld,\"duration_ms\":%lu,"
                "\"motor_time_ms\":%lu,\"pulses\":%u,\"result\":\"%s\","
                "\"events\":%u,\"measurements\":%u,\"schema\":%u}",
                static_cast<unsigned long>(id), static_cast<unsigned long>(session.session_timestamp),
                session.profile_id, session.grind_mode == 1 ? "time" : "weight",
                session.target_weight, static_cast<unsigned long>(session.target_time_ms),
                session.final_weight, session.error_grams, static_cast<long>(session.time_error_ms),
                static_cast<unsigned long>(session.total_time_ms),
                static_cast<unsigned long>(session.total_motor_on_time_ms), session.pulse_count,
                json_escape(String(result)).c_str(), header.event_count, header.measurement_count,
                header.schema_version);
        }
        response->print("]}");
        response->addHeader("Cache-Control", "no-store");
        request->send(response);
    });

    server_.on(AsyncURIMatcher::exact("/api/v1/history/session"), HTTP_GET, [this](AsyncWebServerRequest* request) {
        if (!request->hasParam("id")) {
            request->send(400, "application/json", "{\"error\":\"Session id is required\"}");
            return;
        }
        if (history_is_busy(grind_controller_) || ota_active_.load() ||
            (bluetooth_manager_ && bluetooth_manager_->is_transfer_active())) {
            request->send(409, "application/json", "{\"error\":\"History is busy; try again when the grinder is idle\"}");
            return;
        }
        const String text_id = request->getParam("id")->value();
        for (size_t i = 0; i < text_id.length(); ++i) {
            if (!isDigit(text_id[i])) {
                request->send(400, "application/json", "{\"error\":\"Invalid session id\"}");
                return;
            }
        }
        const uint32_t id = text_id.toInt();
        if (id == 0) {
            request->send(400, "application/json", "{\"error\":\"Invalid session id\"}");
            return;
        }
        char path[48];
        snprintf(path, sizeof(path), SESSION_FILE_FORMAT, static_cast<unsigned long>(id));
        if (!filesystem.exists(path) || !grind_logger.validate_stored_session(id)) {
            request->send(404, "application/json", "{\"error\":\"Session not found\"}");
            return;
        }
        const bool download = request->hasParam("download");
        AsyncWebServerResponse* response = request->beginResponse(
            LittleFS, path, "application/vnd.smartgrind.session", download);
        response->addHeader("Cache-Control", "private, no-store");
        request->send(response);
    });

    server_.on(
        AsyncURIMatcher::exact("/api/v1/screensaver/image"), HTTP_POST,
        [](AsyncWebServerRequest* request) {
            if (request->getResponse()) return;
            auto* state = static_cast<ScreensaverUploadState*>(request->_tempObject);
            if (!state || !state->complete) {
                request->send(400, "application/json", "{\"error\":\"Screensaver image was not received\"}");
                return;
            }
            request->send(state->success ? 200 : 500, "application/json",
                          state->success ? "{\"saved\":true}" : "{\"error\":\"Screensaver upload failed\"}");
        },
        [this](AsyncWebServerRequest* request, String, size_t index,
               uint8_t* data, size_t len, bool final) {
            if (request->getResponse()) return;
            auto* state = static_cast<ScreensaverUploadState*>(request->_tempObject);
            if (index == 0) {
                if (!request_origin_allowed(request)) {
                    request->send(403, "application/json", "{\"error\":\"Request origin is not allowed\"}");
                    return;
                }
                state = static_cast<ScreensaverUploadState*>(calloc(1, sizeof(ScreensaverUploadState)));
                request->_tempObject = state;
                if (!state) {
                    request->send(503, "application/json", "{\"error\":\"Not enough memory to start upload\"}");
                    return;
                }
                if (!bluetooth_manager_ || ota_active_.load() ||
                    (grind_controller_ && grind_controller_->is_active()) ||
                    bluetooth_manager_->is_transfer_active()) {
                    request->send(409, "application/json", "{\"error\":\"Stop the grinder and other transfers before uploading\"}");
                    return;
                }
                if (!bluetooth_manager_->begin_screensaver_image_upload(BLE_IMAGE_EXPECTED_SIZE)) {
                    request->send(400, "application/json", "{\"error\":\"Image must be a 280 x 456 RGB565 frame\"}");
                    return;
                }
                request->onDisconnect([this, state]() {
                    if (state && !state->complete && bluetooth_manager_) {
                        bluetooth_manager_->abort_screensaver_image_upload();
                    }
                });
            }
            if (!state || !bluetooth_manager_) return;
            if (len && !bluetooth_manager_->write_screensaver_image_chunk(data, len)) {
                state->complete = true;
                state->success = false;
                bluetooth_manager_->abort_screensaver_image_upload();
                request->send(500, "application/json", "{\"error\":\"Could not store image data\"}");
                return;
            }
            if (final) {
                state->complete = true;
                state->success = bluetooth_manager_->finish_screensaver_image_upload();
                if (state->success) device_api.mark_settings_dirty();
            }
        });

    server_.on(AsyncURIMatcher::exact("/api/v1/screensaver/image"), HTTP_GET, [this](AsyncWebServerRequest* request) {
        if ((grind_controller_ && grind_controller_->is_active()) || ota_active_.load() ||
            (bluetooth_manager_ && bluetooth_manager_->is_transfer_active())) {
            request->send(409, "application/json", "{\"error\":\"Screensaver image is busy\"}");
            return;
        }
        if (!filesystem.exists(BLE_IMAGE_FILENAME)) {
            request->send(404, "application/json", "{\"error\":\"No custom screensaver is stored\"}");
            return;
        }
        AsyncWebServerResponse* response = request->beginResponse(
            LittleFS, BLE_IMAGE_FILENAME, "application/vnd.smartgrind.rgb565", false);
        response->addHeader("Cache-Control", "private, no-store");
        request->send(response);
    });

    server_.on(AsyncURIMatcher::exact("/api/v1/screensaver/image"), HTTP_DELETE, [this](AsyncWebServerRequest* request) {
        if (!request_origin_allowed(request)) {
            request->send(403, "application/json", "{\"error\":\"Request origin is not allowed\"}");
            return;
        }
        if (!bluetooth_manager_ || ota_active_.load() ||
            (grind_controller_ && grind_controller_->is_active()) ||
            bluetooth_manager_->is_transfer_active()) {
            request->send(409, "application/json", "{\"error\":\"Screensaver image is busy\"}");
            return;
        }
        const bool deleted = bluetooth_manager_->delete_screensaver_image();
        if (deleted) device_api.mark_settings_dirty();
        request->send(deleted ? 200 : 500, "application/json",
                      deleted ? "{\"deleted\":true}" : "{\"error\":\"Could not delete screensaver\"}");
    });

    server_.on(AsyncURIMatcher::exact("/api/v1/ota/prepare"), HTTP_POST, [this](AsyncWebServerRequest* request) {
        const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
        if (is_ota_active()) {
            request->send(409, "application/json", "{\"error\":\"A firmware update is already active\"}");
            return;
        }
        const OtaPreparationState preparation = ota_preparation_state_.load();
        if (preparation == OtaPreparationState::READY) {
            const bool ready = is_ota_ready();
            request->send(ready ? 200 : 409, "application/json",
                          ready ? "{\"ready\":true}" : "{\"error\":\"Update preparation is no longer ready\"}");
            return;
        }
        if (preparation == OtaPreparationState::REQUESTED) {
            request->send(202, "application/json", "{\"preparing\":true}");
            return;
        }
        if (firmware_update_check_active_.load()) {
            request->send(409, "application/json", "{\"error\":\"Wait for the firmware update check to finish\"}");
            return;
        }
        if (!grind_controller_ || grind_controller_->is_active()) {
            request->send(409, "application/json", "{\"error\":\"Stop the grinder before updating firmware\"}");
            return;
        }
        if (bluetooth_manager_ && bluetooth_manager_->is_transfer_active()) {
            request->send(409, "application/json", "{\"error\":\"Wait for the Bluetooth transfer to finish\"}");
            return;
        }
        if (!request_ota_preparation()) {
            request->send(409, "application/json", "{\"error\":\"Another operation is using the grinder\"}");
            return;
        }
        request->send(202, "application/json", "{\"preparing\":true}");
    });

    server_.on(AsyncURIMatcher::exact("/api/v1/ota/github"), HTTP_POST, [this](AsyncWebServerRequest* request) {
        if (!request_origin_allowed(request)) {
            request->send(403, "application/json", "{\"error\":\"Request origin is not allowed\"}");
            return;
        }
        if (!request->hasParam("tag", true)) {
            request->send(400, "application/json", "{\"error\":\"Release tag is required\"}");
            return;
        }
        const String tag = request->getParam("tag", true)->value();
        if (!valid_release_tag(tag)) {
            request->send(400, "application/json", "{\"error\":\"Release tag is invalid\"}");
            return;
        }
        if (!start_github_ota(tag)) {
            request->send(409, "application/json", "{\"error\":\"Prepare the update before installing\"}");
            return;
        }
        request->send(202, "application/json", "{\"accepted\":true}");
    });

    server_.on(
        AsyncURIMatcher::exact("/api/v1/ota"), HTTP_POST,
        [](AsyncWebServerRequest* request) {
            if (request->getResponse()) return;
            OtaRequestState* state = static_cast<OtaRequestState*>(request->_tempObject);
            if (!state || !state->complete) {
                request->send(400, "text/plain", "Firmware file was not received");
                return;
            }
            if (!state->success) {
                request->send(500, "text/plain", "Firmware update failed");
                return;
            }
            request->send(200, "text/plain", "Firmware accepted; Smart Grind is restarting");
        },
        [this](AsyncWebServerRequest* request, String filename, size_t index,
               uint8_t* data, size_t len, bool final) {
            handle_ota_upload(request, filename, index, data, len, final);
        });
}

bool DeviceWebServer::start_github_ota(const String& tag) {
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    if (!is_ota_ready()) return false;
    bool expected_inactive = false;
    if (!ota_active_.compare_exchange_strong(expected_inactive, true)) return false;
    ota_preparation_state_.store(OtaPreparationState::IDLE);
    ota_received_.store(0);
    ota_total_.store(0);
    String* task_tag = new (std::nothrow) String(tag);
    if (!task_tag || xTaskCreate(github_ota_task, "github_ota", OTA_DOWNLOAD_TASK_STACK,
                                 task_tag, 1, nullptr) != pdPASS) {
        delete task_tag;
        finish_ota(false);
        return false;
    }
    return true;
}

void DeviceWebServer::github_ota_task(void* parameter) {
    String* task_tag = static_cast<String*>(parameter);
    const String tag = task_tag ? *task_tag : String();
    delete task_tag;
    device_web_server.perform_github_ota(tag);
    vTaskDelete(nullptr);
}

void DeviceWebServer::perform_github_ota(const String& tag) {
    const String filename =
        "smart-grind-by-weight-" + tag + HW_RELEASE_FIRMWARE_SUFFIX + ".bin";
    const String url = String(GITHUB_RELEASE_MIRROR_BASE) + tag + "/" + filename;
    LOG_BLE("[WEB OTA] Downloading %s from release mirror\n", filename.c_str());
    if (hardware_manager_ && hardware_manager_->get_grinder()) {
        hardware_manager_->get_grinder()->stop();
    }

    WiFiClientSecure secure_client;
    secure_client.setCACertBundle(
        x509_crt_imported_bundle_bin_start,
        static_cast<size_t>(x509_crt_imported_bundle_bin_end -
                            x509_crt_imported_bundle_bin_start));
    secure_client.setTimeout(15000);
    secure_client.setHandshakeTimeout(15);
    HTTPClient http;
    http.useHTTP10(true);
    http.setConnectTimeout(15000);
    http.setTimeout(15000);
    http.setFollowRedirects(HTTPC_STRICT_FOLLOW_REDIRECTS);
    http.setUserAgent("SmartGrind-OTA/1");
    http.addHeader("Cache-Control", "no-cache");
    if (!http.begin(secure_client, url)) {
        LOG_BLE("[WEB OTA] Could not initialise release-mirror connection\n");
        finish_ota(false);
        return;
    }
    const int status = http.GET();
    if (status != HTTP_CODE_OK) {
        char tls_error[128]{};
        const int tls_error_code = secure_client.lastError(tls_error, sizeof(tls_error));
        LOG_BLE("[WEB OTA] Release download failed: HTTP %d (%s), TLS %d (%s), "
                "epoch %lld, heap %u, largest %u\n",
                status, HTTPClient::errorToString(status).c_str(), tls_error_code, tls_error,
                static_cast<long long>(time(nullptr)),
                static_cast<unsigned int>(
                    heap_caps_get_free_size(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT)),
                static_cast<unsigned int>(
                    heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT)));
        http.end();
        finish_ota(false);
        return;
    }
    const int content_length = http.getSize();
    const esp_partition_t* target = esp_ota_get_next_update_partition(nullptr);
    if (!target || content_length <= 0 || static_cast<size_t>(content_length) > target->size) {
        LOG_BLE("[WEB OTA] Invalid image size: %d\n", content_length);
        http.end();
        finish_ota(false);
        return;
    }
    WiFiClient* stream = http.getStreamPtr();
    uint8_t first_byte = 0;
    if (!stream || !ota_wait_for_data(*stream, [] { return millis(); },
                                      [] { vTaskDelay(pdMS_TO_TICKS(2)); }, 15000) ||
        stream->readBytes(&first_byte, 1) != 1) {
        LOG_BLE("[WEB OTA] Download timed out or disconnected before the first image byte\n");
        http.end();
        finish_ota(false);
        return;
    }
    if (first_byte != 0xE9) {
        LOG_BLE("[WEB OTA] Download is not an ESP32 application image\n");
        http.end();
        finish_ota(false);
        return;
    }
    if (!web_firmware_update.begin(static_cast<size_t>(content_length), U_FLASH) ||
        web_firmware_update.write(&first_byte, 1) != 1) {
        LOG_BLE("[WEB OTA] Could not open or write inactive partition: %s\n",
                web_firmware_update.errorString());
        http.end();
        finish_ota(false);
        return;
    }
    ota_total_.store(static_cast<size_t>(content_length));
    ota_received_.store(1);
    uint8_t buffer[4096];
    uint32_t idle_deadline = millis() + 15000;
    while (http.connected() && ota_received_.load() < ota_total_.load()) {
        const size_t available = stream->available();
        if (available == 0) {
            if (static_cast<int32_t>(millis() - idle_deadline) >= 0) break;
            vTaskDelay(pdMS_TO_TICKS(2));
            continue;
        }
        const size_t wanted = std::min(available, sizeof(buffer));
        const int read = stream->readBytes(buffer, wanted);
        if (read <= 0) break;
        if (web_firmware_update.write(buffer, static_cast<size_t>(read)) != static_cast<size_t>(read)) {
            LOG_BLE("[WEB OTA] Flash write failed: %s\n", web_firmware_update.errorString());
            web_firmware_update.abort();
            http.end();
            finish_ota(false);
            return;
        }
        ota_received_.fetch_add(static_cast<size_t>(read));
        idle_deadline = millis() + 15000;
    }
    http.end();
    const bool complete = ota_received_.load() == ota_total_.load();
    const bool valid = complete && web_firmware_update.end(true);
    if (!valid) {
        if (!complete) web_firmware_update.abort();
        LOG_BLE("[WEB OTA] Download incomplete or invalid (%lu/%lu): %s\n",
                static_cast<unsigned long>(ota_received_.load()),
                static_cast<unsigned long>(ota_total_.load()), web_firmware_update.errorString());
        finish_ota(false);
        return;
    }
    LOG_BLE("[WEB OTA] GitHub firmware validated (%lu bytes)\n",
            static_cast<unsigned long>(ota_received_.load()));
    finish_ota(true);
}

void DeviceWebServer::handle_ota_upload(AsyncWebServerRequest* request, const String& filename,
                                         size_t index, uint8_t* data, size_t len, bool final) {
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    if (request->getResponse()) return;

    OtaRequestState* state = static_cast<OtaRequestState*>(request->_tempObject);
    if (index == 0) {
        if (!is_ota_ready()) {
            request->send(409, "text/plain", "Prepare the firmware update before uploading");
            return;
        }
        bool expected_inactive = false;
        if (!ota_active_.compare_exchange_strong(expected_inactive, true)) {
            request->send(409, "text/plain", "Another firmware update is already active");
            return;
        }
        ota_preparation_state_.store(OtaPreparationState::IDLE);
        state = static_cast<OtaRequestState*>(calloc(1, sizeof(OtaRequestState)));
        request->_tempObject = state;
        if (!state) {
            finish_ota(false);
            request->send(503, "text/plain", "Not enough memory to start firmware update");
            return;
        }
        state->token = operation_token_;
        if (!filename.endsWith(".bin") || len == 0 || data[0] != 0xE9) {
            finish_ota(false);
            request->send(400, "text/plain", "Not a valid ESP32 firmware image");
            return;
        }
        if (!grind_controller_ || grind_controller_->is_active()) {
            finish_ota(false);
            request->send(409, "text/plain", "Stop the grinder before updating firmware");
            return;
        }
        if (bluetooth_manager_ && bluetooth_manager_->is_transfer_active()) {
            finish_ota(false);
            request->send(409, "text/plain", "Wait for the Bluetooth transfer to finish");
            return;
        }
        const size_t internal_heap = heap_caps_get_free_size(MALLOC_CAP_INTERNAL | MALLOC_CAP_8BIT);
        if (internal_heap < OTA_MIN_INTERNAL_HEAP) {
            finish_ota(false);
            request->send(503, "text/plain", "Prepare the update first so Bluetooth can release memory");
            return;
        }
        const esp_partition_t* target = esp_ota_get_next_update_partition(nullptr);
        if (!target || request->contentLength() > target->size + 8192U) {
            finish_ota(false);
            request->send(413, "text/plain", "Firmware image is too large");
            return;
        }
        if (hardware_manager_ && hardware_manager_->get_grinder()) {
            hardware_manager_->get_grinder()->stop();
        }
        if (!web_firmware_update.begin(UPDATE_SIZE_UNKNOWN, U_FLASH)) {
            LOG_BLE("[WEB OTA] Update.begin failed: %s\n", web_firmware_update.errorString());
            finish_ota(false);
            request->send(500, "text/plain", "Could not open the inactive firmware partition");
            return;
        }
        ota_received_.store(0);
        ota_total_.store(request->contentLength());
        request->onDisconnect([this, state]() {
            const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
            if (ota_active_.load() && state && !state->complete &&
                operation_interlock().owns(state->token) && state->token == operation_token_) {
                LOG_BLE("[WEB OTA] Client disconnected; aborting incomplete upload\n");
                web_firmware_update.abort();
                finish_ota(false);
            }
        });
        LOG_BLE("[WEB OTA] Receiving %s\n", filename.c_str());
    }

    if (!state || state->complete || !ota_active_.load() ||
        state->token != operation_token_ || !operation_interlock().owns(state->token)) return;
    if (len > 0 && web_firmware_update.write(data, len) != len) {
        LOG_BLE("[WEB OTA] Write failed at %lu: %s\n",
                static_cast<unsigned long>(ota_received_.load()), web_firmware_update.errorString());
        web_firmware_update.abort();
        state->complete = true;
        state->success = false;
        finish_ota(false);
        request->send(500, "text/plain", "Firmware write failed");
        return;
    }
    ota_received_.fetch_add(len);

    if (final) {
        state->complete = true;
        state->success = web_firmware_update.end(true);
        if (!state->success) {
            LOG_BLE("[WEB OTA] Image validation failed: %s\n", web_firmware_update.errorString());
            finish_ota(false);
            return;
        }
        LOG_BLE("[WEB OTA] Firmware validated (%lu bytes)\n",
                static_cast<unsigned long>(ota_received_.load()));
        finish_ota(true);
    }
}

void DeviceWebServer::finish_ota(bool success) {
    const std::lock_guard<std::recursive_mutex> ota_lock(ota_mutex_);
    if (!success) web_firmware_update.abort();
    ota_failed_.store(!success);
    ota_active_.store(false);
    if (success) {
        ota_bluetooth_stopped_.store(false);
        ota_preparation_state_.store(OtaPreparationState::IDLE);
        reboot_at_ms_.store(millis() + OTA_REBOOT_DELAY_MS);
        reboot_pending_.store(true);
    } else {
        recover_from_ota_failure();
    }
}
